import json
from pathlib import Path
root=Path(__file__).resolve().parents[1];phase=root/'experiments/apertus-v15-phase2'
s=json.loads((root/'deployment/v15-selection.json').read_text());f=json.loads((root/s['phase2_results']).read_text());c=json.loads((phase/'context-results.json').read_text());b=json.loads((root/'experiments/budget.json').read_text());m=f['final_validation_metrics'];d=f['bounded_neighbor_diversity_evidence_diagnostics'];cal=m['calibration'];choice=f['final_choice']
lines=['# Phase2: resumen científico de Apertus OST','',
'## 1. Controles de dependencia del documento','',
'| Entrada del sistema original | Macro-F1 de validación |','|---|---:|',
'| Folleto correcto |0.894461|','| Solo afirmación, cabeza entrenada exclusivamente en train |0.699640|',
'| Folleto de otro evento, mismo idioma; seed42 |0.565341|','| Folleto de otro evento, mismo idioma; seed1337 |0.553328|','| Premisa vacía, cabeza original congelada |0.210229|','| Premisa genérica, cabeza original congelada |0.174688|','',
'La caída con folletos incorrectos respalda dependencia del contexto. El buen resultado sin documento muestra señales de clase en las afirmaciones; estos controles no demuestran grounding semántico universal. Las etiquetas originales miden retención bajo intervenciones, no la verdad NLI de las nuevas parejas.','',
'Controles de la cabeza/contexto final: '+', '.join(f"{k}={v['original_label_retention_metrics']['macro_f1']:.6f}" for k,v in f['context_matched_controls'].items())+'. Todos los controles registrados exigidos para la selección pasan.','',
'## 2. Contexto y frontera observada','',
'| Contexto/cabeza correspondiente | Macro-F1 | Tokens medios | Segundos medidos en caché |','|---|---:|---:|---:|']
for name,v in c['comparisons'].items():
 q=v['matched_head'];lines.append(f"|{name}|{q['macro_f1']:.6f}|{q['average_context_tokens']:.0f}|{q['average_latency_seconds']:.3f}|")
full=f['full_recheck']['metrics'];lines.extend([f"|Original full, comprobación A6000|{full['macro_f1']:.6f}|{full['average_context_tokens']:.0f}|{full['average_latency_seconds']:.3f}|",'',
'La frontera global observada de F1/tokens/latencia contiene1k,2k,8k y prefix2k.4k fue la elección de eficiencia registrada bajo restricciones adicionales por clase e idioma; no se presenta como punto global no dominado. La alternativa8k se registró separadamente tras observar una mejora material. La selección de arquitectura usa validación y no es descubrimiento ciego. Las latencias de contextos compactos suman codificación, recuperación y cabeza por separado; no incluyen arranque, extracción PDF ni HTTP.','',
'## 3. Evidencia','',
f"Se verificaron texto exacto, página, offsets y SHA del PDF. El solapamiento lexical5gram con referencias para {choice} es un diagnóstico de desarrollo, no la métrica oficial. Referencias nunca son necesarias en producción. Se ejecutaron **{d['evidence_sufficiency_n']}** inferencias reales solo con las1–2 citas propuestas: preservación **{d['evidence_decision_preservation_rate']:.1%}**; **{d['evidence_strict_reduction_n']}** contextos fueron estrictamente reducidos, con preservación **{d['evidence_decision_preservation_when_strictly_reduced']:.1%}**. Esto mide sensibilidad, no prueba humana de suficiencia ni atribución.",'',
'La inspección cualitativa de9 casos por idioma/clase está en evidence-audit.json. Las citas de salida siguen siendo contexto fuente ordenado, no pruebas mínimas certificadas. Neutral requiere cautela: no encontrar evidencia en el contexto seleccionado no prueba ausencia en todo el folleto. La posible ambigüedad de alcance de ost-v1.1-0732 se conserva sin cambiar etiquetas. Las expansiones por vecinos/diversidad usan90 casos fijos y no se adoptan a partir de esa pequeña muestra.','',
'## 4. Arquitectura congelada','',f'**{choice}**, recuperación híbrida E5/BM25, pasajes íntegros con presupuesto de tokens nativo, Apertus v1.5 congelado y cabeza logística multiclase entrenada/calibrada solo con train. Sin LoRA, QLoRA,70B, cuantización ni router adaptativo.','',
'```mermaid','flowchart LR',' PDF[Folleto PDF] --> Parse[Pasajes con página y offsets]',' Parse --> Retrieve[Recuperación E5 y BM25]',' Claim[Afirmación DE FR IT] --> Retrieve',f' Retrieve --> Context[Contexto {choice}]',' Context --> Apertus[Apertus v1.5 congelado]',' Apertus --> Head[Cabeza calibrada con train]',' Head --> Label[Clase 0 1 2 y confianza]',' Context --> Quotes[Citas fuente y páginas]',' Label --> Metrics[Tokens y tiempo]','```','',
f"Validación final: F1 **{m['macro_f1']:.6f}**; cross-language **{m['cross_lingual']['macro_f1']:.6f}**;207 parejas deduplicadas **{f['deduplicated_macro_f1']:.6f}**. CLI con3 PDFs cross-language y petición real de subida/predicción del frontend se verificaron sobre GPU. El Docker frontend requiere el backend nativo configurado; las GPUs desechables se destruyeron tras archivar las pruebas.",'',
'## 5. Calibración','',f"ECE10 bins **{cal['ece']:.6f}** · Brier **{cal['brier_score']:.6f}** · NLL **{cal['negative_log_likelihood']:.6f}**. Temperatura elegida con OOF de train; no recalibración en validación.",'',
'| Confianza | n | Exactitud | Confianza media |','|---|---:|---:|---:|'])
for q in f['confidence_buckets']:
 fmt=lambda value:f'{value:.3f}' if value is not None else '—'
 lines.append(f"|{q['low']:.2f}–{q['high']:.2f}|{q['n']}|{fmt(q['accuracy'])}|{fmt(q['mean_confidence'])}|")
semantic_path=phase/'semantic-reference-diagnostic.json'
if semantic_path.exists():
 semantic=json.loads(semantic_path.read_text());q=semantic['entailment_contradiction']['conditions'].get(choice)
 if q:lines+=['',f"Diagnóstico semántico complementario: presencia del pasaje fuente más próximo a la referencia E5 **{q['top1_presence_rate']:.1%}** en casos Entailment/Contradiction. Es una aproximación dependiente del mismo recuperador, no recall de evidencia humana ni evaluación oficial; véase semantic-reference-diagnostic.json."]
lines+=['', 'Los umbrales adaptativos solo se simularon con caché, contabilizando ambos forwards al escalar. No se adopta complejidad adicional. Las probabilidades de controles con documento incorrecto no se interpretan como calibración de etiquetas NLI verdaderas.','',
'## 6. Cómputo','',f"Gasto Vast total observado: **USD{b['actual_spend']:.4f}**. Gasto incremental Phase2: **USD{b['phase2']['additional_observed_spend_usd']:.4f}**. Crédito observado restante: **USD{float(b['account_credit_observed'])+float(b.get('account_balance_observed') or 0):.4f}**. Instancias de esta tarea activas: **{len(b['active_instance_ids'])}**, destrucción verificada por API paginada. Se conservó la reserva de USD2 y el límite adicional de USD4.50. Contabilidad del proveedor sujeta a cargos tardíos; budget.json y resource-audit.json contienen timestamps, precios, duración y observaciones por etapa.",'',
'## 7. Conclusión científica','',
f"**La hipótesis recibe apoyo parcial en este benchmark de desarrollo.** Las representaciones de Apertus congelado permiten una cabeza ligera con F1{m['macro_f1']:.3f}, y los controles de folletos incorrectos reducen materialmente la retención. El contexto baja de aproximadamente14106 a{m['average_context_tokens']:.0f} tokens sin sacrificar la calidad de validación. Esto justifica la arquitectura final, no una afirmación universal de razonamiento o generalización.",'',
'Persisten señales en las afirmaciones, solo3 eventos y2 unidades conectadas de validación, duplicados/paráfrasis, posible ambigüedad de alcance y evidencia no certificada. Se requiere evaluación en nuevos folletos independientes. Los310 ejemplos consumidos nunca se reabrieron en Phase2: su F1 histórico0.899920 pertenece únicamente al sistema original full, no a la nueva cabeza compacta. No se justifica gastar el remanente en LoRA con esta evidencia.','',
'Fuente completa: [technical_report.md](../../technical_report.md); métricas: context-results.json, final-results.json y accuracy-results.json cuando exista; errores: selected-error-analysis.jsonl.']
(phase/'research-summary.md').write_text('\n'.join(lines)+'\n')
print('Concise seven-part research summary written')
